'use client';

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { createContext, useState, useContext } from "react";
import { Order } from "../../types/prod";

interface OrdersContextType {
  orders: Order[];
  setOrders: React.Dispatch<React.SetStateAction<Order[]>>;
}

const OrdersContext = createContext<OrdersContextType | undefined>(undefined);

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const useOrderContext = () => {
  const context = useContext(OrdersContext);
  if (!context) {
    throw new Error('useOrders must be used within an OrdersProvider');
  }
  return context;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [orders, setOrders] = useState<Order[]>([]);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <nav>
        <Link href='/dashboard'> Dashboard </Link>
        <Link href='/orders'> Order List </Link>
        {/* <Link href='/orders/newOrder'> New Order </Link> */}
      </nav>
      <OrdersContext.Provider value={{orders, setOrders}}>
          {children}
      </OrdersContext.Provider>
      </body>
    </html>
  );
}
